name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - test 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Merge test → main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: test
          target_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
